### ISSUE TITLE
Decorator support

### ISSUE THREAD

**Issue by jhen0409** [zalmoxisus/mobx-remotedev#11]
I think it will be cleaner if we have decorator support:

```js
@remotedev({ /* config */ })
export default class Counter {
  @observable counter = 0

  ...
}
```

@zalmoxisus, if you agreed I'll make a PR. :)

**Comment by zalmoxisus** [comment]
Definitely, it would be nice to have! :)

**Comment by zalmoxisus** [comment]
It's up in `v0.2.3`.
