### ISSUE TITLE
[mobx] Invariant failed: Cannot obtain atom from [object Object]

### ISSUE THREAD

**Issue by DavidStummer** [zalmoxisus/mobx-remotedev#21]
This is only happening if I wrap a class with remotedev method. i.e. the first call to remotedev succeeds:

![screen shot 2017-04-26 at 17 19 13](https://cloud.githubusercontent.com/assets/4497624/25444866/86cb1afe-2aa4-11e7-9244-29776455085e.png)

![screen shot 2017-04-26 at 17 18 58](https://cloud.githubusercontent.com/assets/4497624/25444883/949648fc-2aa4-11e7-9eec-59f0b95c1001.png)

**Comment by zalmoxisus** [comment]
Sorry, I missed the issue. Did you managed to solve it? If not, please provide a repro or modify one of [our examples](https://github.com/zalmoxisus/mobx-remotedev/tree/master/examples) to reproduce it.

**Comment by DavidStummer** [comment]
The issue I was having was actually related to incorrect babelrc settings, leading to mobx not working with classes, only simple objects. Your lib was not working as a side effect. sorry for the confusion.

**Comment by brankeye** [comment]
@DavidStummer do you recall the particular babel settings that caused the issue? I'm encountering the same thing right now, struggling to fix.

**Comment by rpmonteiro** [comment]
Same here... @DavidStummer  how did you fix it?

**Comment by reetou** [comment]
@rpmonteiro Seems like I fixed it.
I had a class with @actions and constructor with other stores inside one. Adding an `@observable s = false`, for example, fixed this issue.

**Comment by tranquan** [comment]
@reetou Hi, I'm facing the same issue. Adding a dummy @observer can solve the crash but the RemoveDev tools cannot log the state anymore. Do you have any suggestion?
I'm using mobx with react-native

**Comment by Kirill-Cherkalov** [comment]
I had a similar issue. I have rootStore class where I combine all stores. And I fixed this issue when added any @observable field to root store. Thanks to @reetou for help.
