### ISSUE TITLE
Multiple values in BlackList/Whitelist filters not working

### ISSUE THREAD

**Issue by brandiqa** [zalmoxisus/mobx-remotedev#22]
I hope am doing this correctly:

```javascript
const contactConfig = {
  name:'Contact Store',
  global:true,
  filters: {
    blacklist: ['add','splice']
  }
};
```

The above blacklist array doesn't work at all. But if I do blacklist:['add'] or blacklist:['splice'] it works, but not with multiple values. I've also tried blacklist: [/add/,/splice/] and it still doesn't work. The same case applies with whitelist.

**Comment by zalmoxisus** [comment]
Yes, the docs are misleading here. That functionality is present in the extension, but not [here](https://github.com/zalmoxisus/mobx-remotedev/blob/master/src/filters.js). For now you can use something like `blacklist: /add|splice/`.

**Comment by brandiqa** [comment]
Thanks! That works perfectly. Hope the docs get updated
