### ISSUE TITLE
remotedev is trying to access computed properties before object initialized 

### ISSUE THREAD

**Issue by farwayer** [zalmoxisus/mobx-remotedev#23]
```js
class Test {
  items = [];

  @computed get filtered() {
    return this.items.filter(() => true);
  }
}
const test = new (remoteDev(Test));
```

```js
Cannot read property 'filter' of undefined
```

**Comment by zalmoxisus** [comment]
Thanks for the report.

We're listing all methods in order to be able to select them to call remotely from the monitor, but we should skip getters and setters.

Fixed in `0.2.7`. Pleas let me know if it now works.

**Comment by farwayer** [comment]
Look like fixed now. Thank you!

**Comment by farwayer** [comment]
Are any plans to release new version to npm?

**Comment by zalmoxisus** [comment]
Thanks for the heads-up. I thought it's there. Fixed now.
