### ISSUE TITLE
Observable map?

### ISSUE THREAD

**Issue by FredyC** [zalmoxisus/mobx-remotedev#27]
Is it possible to use remotedev on observable Map? I tried `remotedev(observable(new Map())`, it is visible in the Redux DevTools, but no actions or state is shown there.

**Comment by kubk** [comment]
@FredyC sorry for bothering, you might want to try this logger: https://github.com/kubk/mobx-log
It does support Maps & Sets: https://github.com/kubk/mobx-log/pull/10

**Comment by danielkcz** [comment]
I guess I will close it. Four years is long time I don't know why I needed this :)
