### ISSUE TITLE
Use devtools in React Native with Mobx State Tree

### ISSUE THREAD

**Issue by alexlevy0** [zalmoxisus/mobx-remotedev#28]
Hello,

I'm trying to use mobx-remotedev with React Native and MobX-State-Tree but I don't know how to do. 
I tried with ```export default remotedev(AppStore, { global: true, remote: true })``` in my rootStore but I get an error ```Unhandled JS Exception: Cannot read property 'create' of undefined``` cause I create the tree with ```const appStore = AppStore.create({ users: {} }, { logger: logger })``` 

Can you orient me?

Thanks for readding

**Comment by HaveF** [comment]
@alexlevy0 I see your same issue in [mobxjs/mobx-state-tree](https://github.com/mobxjs/mobx-state-tree/issues/367).

What have you done at last? Did it works?
