### ISSUE TITLE
"export 'isStrictModeEnabled' (imported as 'mobx') was not found in 'mobx'"

### ISSUE THREAD

**Issue by A11oW** [zalmoxisus/mobx-remotedev#42]
When import remotedev from 'mobx-remotedev', I have error: "export 'isStrictModeEnabled' (imported as 'mobx') was not found in 'mobx'"

mobx: 5.9.0,
mobx-remotedev: 0.3.4

**Comment by BlackFenix2** [comment]
I think we have a PR to address this issue:https://github.com/zalmoxisus/mobx-remotedev/pull/41

**Comment by BlackFenix2** [comment]
Im closing out this issue, https://github.com/zalmoxisus/mobx-remotedev/pull/41 addresses the type error for the depreciated isStrictModeEnabled method
