### ISSUE TITLE
With HMR-hot module reloads when I use `global: true` I get You've already defined a global store is there any way to suppress this

### ISSUE THREAD

**Issue by tktaofik** [zalmoxisus/mobx-remotedev#44]
<img width="975" alt="screen shot 2019-02-21 at 12 03 06 am" src="https://user-images.githubusercontent.com/8204154/53144896-1796a700-356c-11e9-8cac-e9f46f8716ff.png">

**Comment by tktaofik** [comment]
I opened a PR to fix the issue PR: https://github.com/zalmoxisus/mobx-remotedev/pull/45

**Comment by zalmoxisus** [comment]
Thanks for the contribution! It's in `0.3.6`.
