### ISSUE TITLE
examples/counter not works

### ISSUE THREAD

**Issue by HaveF** [zalmoxisus/mobx-remotedev#8]
1. Install chrome extension
2. use examples/counter, not works
3. update examples/counter/package.json

  ```
-    "mobx-remotedev": "^0.0.1",
+    "mobx-remotedev": "^0.2.2",
```
   ```
-    "jsdom": "^5.6.1",
-    "mocha": "^2.2.5",
-    "node-libs-browser": "^0.5.2",
+    "jsdom": "^9.5.0",
+    "mocha": "^3.1.0",
+    "node-libs-browser": "^1.0.0",
```

still not works. The browser is blank.
No error at terminal:
```
➜  counter git:(master) ✗ npm start

> redux-counter-example@0.0.0 start /Users/HaveF/Desktop/mobx/mobx-remotedev/examples/counter
> node server.js

==> 🌎  Listening on port 4001. Open up http://localhost:4001/ in your browser.
webpack built d6f57debc790c97f8f46 in 3999ms
```

error at browser console:
>Uncaught Error: [mobx] Invariant failed: Cannot obtain atom from [object Object]

![2016-10-02 8 10 21](https://cloud.githubusercontent.com/assets/54462/19020480/70c58736-88dc-11e6-9967-337a9583d219.png)

**Comment by zalmoxisus** [comment]
Thanks for the report. I know the examples are a bit confusing. You should change
```js
import remotedev from '../../../src/dev'; // import remotedev from 'mobx-remotedev/lib/dev';
```
to
```js
import remotedev from '../../../src/dev'; // import remotedev from 'mobx-remotedev/lib/dev';
```
of [this line](https://github.com/zalmoxisus/mobx-remotedev/blob/master/examples/counter/stores/appState.js#L2).

You get that error message because the `appState` and `mobx-remotedev` use 2 different mobx instances (one from the `examples/counter/node_package` and another one from `node_package`.

**Comment by HaveF** [comment]
Thanks for your explanation. I see, these examples are for dev purpose.

**Comment by zalmoxisus** [comment]
Yes, but they are indeed confusing, so I've just removed them in https://github.com/zalmoxisus/mobx-remotedev/commit/dd8b833ebaba84268152be022e6fa456ec2bf3b3.
